version: '3'

services:
  node: 
    container_name: cuc_cung_server
    build:
      context: ./server
      dockerfile: DockerFile.server
    ports: 
      - 4000:4000
      - 3000:3000
    depends_on:
      - mongo-express
      - blockchain
    volumes:
      - ./server:/app

  blockchain:
    container_name: blockchain
    build:
      context: ./blockchain
      dockerfile: DockerFile.blockchain
    command: >
      bash -c "
        npm install &&
        source /root/.nvm/nvm.sh &&
        npm start
      "
    volumes:
      - ./blockchain:/app

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_ROOT_DATABASE: ${DB_NAME}
    volumes:
      - database:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8888:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASSWORD}@mongo:27017/


volumes:
    database:
